# The URL the site will be built for
base_url = "https://osamasalem.github.io/"
title = "Amaso Melas"
slugify.taxonomies = "on"
taxonomies = [{ name = "tags", feed = true }]

[markdown]
external_links_target_blank = true

[markdown.highlighting]
theme = "ayu-dark"

[extra]
# Put all your custom variables here
